address=/zionode.com/192.168.137.203

# Wildcard for all zionode.com subdomains
address=/.zionode.com/192.168.137.203

# Specific overrides
address=/s1.zionode.com/192.168.137.203
address=/s2.zionode.com/192.168.137.201
